name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository #git-clone main
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install Dependencies
      run: npm install
    - name: tsc && vite build
      run: npm run build
    - name: Test
      run: npm run test
